version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile # The Dockerfile for your API
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__UsersDb=Server=sqlserver,1433;Database=Users;User Id=sa;Password=SuperSecret1;
    dns: 
      - 8.8.8.8

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperSecret1
      - MSSQL_DATABASE=Users
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local
  
